# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: highbar/coordinator.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'highbar/coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from highbar import state_pb2 as highbar_dot_state__pb2
from highbar import commands_pb2 as highbar_dot_commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19highbar/coordinator.proto\x12\nhighbar.v1\x1a\x13highbar/state.proto\x1a\x16highbar/commands.proto\"c\n\x10HeartbeatRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\r\x12\x15\n\rengine_sha256\x18\x03 \x01(\t\x12\x16\n\x0eschema_version\x18\x04 \x01(\t\"Y\n\x11HeartbeatResponse\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65\x63hoed_frame\x18\x02 \x01(\r\x12\x16\n\x0eschema_version\x18\x03 \x01(\t\"D\n\x17\x43ommandChannelSubscribe\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x16\n\x0eschema_version\x18\x02 \x01(\t\"R\n\x07PushAck\x12\x19\n\x11messages_received\x18\x01 \x01(\x04\x12\x14\n\x0cmax_seq_seen\x18\x02 \x01(\x04\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t2\xf2\x01\n\x12HighBarCoordinator\x12H\n\tHeartbeat\x12\x1c.highbar.v1.HeartbeatRequest\x1a\x1d.highbar.v1.HeartbeatResponse\x12;\n\tPushState\x12\x17.highbar.v1.StateUpdate\x1a\x13.highbar.v1.PushAck(\x01\x12U\n\x12OpenCommandChannel\x12#.highbar.v1.CommandChannelSubscribe\x1a\x18.highbar.v1.CommandBatch0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'highbar.coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=86
  _globals['_HEARTBEATREQUEST']._serialized_end=185
  _globals['_HEARTBEATRESPONSE']._serialized_start=187
  _globals['_HEARTBEATRESPONSE']._serialized_end=276
  _globals['_COMMANDCHANNELSUBSCRIBE']._serialized_start=278
  _globals['_COMMANDCHANNELSUBSCRIBE']._serialized_end=346
  _globals['_PUSHACK']._serialized_start=348
  _globals['_PUSHACK']._serialized_end=430
  _globals['_HIGHBARCOORDINATOR']._serialized_start=433
  _globals['_HIGHBARCOORDINATOR']._serialized_end=675
# @@protoc_insertion_point(module_scope)
