# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from highbar import commands_pb2 as highbar_dot_commands__pb2
from highbar import coordinator_pb2 as highbar_dot_coordinator__pb2
from highbar import state_pb2 as highbar_dot_state__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in highbar/coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HighBarCoordinatorStub(object):
    """The coordinator exposes this service. The plugin dials out to it
    from within spring-headless. Multiple observers/AI clients attach to
    the coordinator, which fans out per match.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/highbar.v1.HighBarCoordinator/Heartbeat',
                request_serializer=highbar_dot_coordinator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=highbar_dot_coordinator__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.PushState = channel.stream_unary(
                '/highbar.v1.HighBarCoordinator/PushState',
                request_serializer=highbar_dot_state__pb2.StateUpdate.SerializeToString,
                response_deserializer=highbar_dot_coordinator__pb2.PushAck.FromString,
                _registered_method=True)
        self.OpenCommandChannel = channel.unary_stream(
                '/highbar.v1.HighBarCoordinator/OpenCommandChannel',
                request_serializer=highbar_dot_coordinator__pb2.CommandChannelSubscribe.SerializeToString,
                response_deserializer=highbar_dot_commands__pb2.CommandBatch.FromString,
                _registered_method=True)


class HighBarCoordinatorServicer(object):
    """The coordinator exposes this service. The plugin dials out to it
    from within spring-headless. Multiple observers/AI clients attach to
    the coordinator, which fans out per match.
    """

    def Heartbeat(self, request, context):
        """Plugin → coordinator heartbeat. Proves the client-mode wire works
        from inside spring. Sent every N frames; coordinator echoes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushState(self, request_iterator, context):
        """Phase B — plugin streams StateUpdate messages to the coordinator.
        One stream per plugin instance, opened at gateway startup, kept
        alive for the lifetime of the match. First message is a
        PushStateInit-bearing StateUpdate? No — we keep it simple: plain
        StateUpdate messages per frame, coordinator demuxes by peer.
        Terminal PushAck carries the sum of seqs received so the plugin
        can log a final reconciliation line.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenCommandChannel(self, request, context):
        """Phase C — coordinator → plugin command stream. Plugin subscribes
        once at startup with CommandChannelSubscribe; coordinator sends
        CommandBatch messages as external AI-role clients submit them.
        Plugin's reader thread pushes each received batch onto the
        engine-thread CommandQueue, where DrainCommandQueue picks them up
        and dispatches on the next frame tick.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HighBarCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=highbar_dot_coordinator__pb2.HeartbeatRequest.FromString,
                    response_serializer=highbar_dot_coordinator__pb2.HeartbeatResponse.SerializeToString,
            ),
            'PushState': grpc.stream_unary_rpc_method_handler(
                    servicer.PushState,
                    request_deserializer=highbar_dot_state__pb2.StateUpdate.FromString,
                    response_serializer=highbar_dot_coordinator__pb2.PushAck.SerializeToString,
            ),
            'OpenCommandChannel': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenCommandChannel,
                    request_deserializer=highbar_dot_coordinator__pb2.CommandChannelSubscribe.FromString,
                    response_serializer=highbar_dot_commands__pb2.CommandBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'highbar.v1.HighBarCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('highbar.v1.HighBarCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HighBarCoordinator(object):
    """The coordinator exposes this service. The plugin dials out to it
    from within spring-headless. Multiple observers/AI clients attach to
    the coordinator, which fans out per match.
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarCoordinator/Heartbeat',
            highbar_dot_coordinator__pb2.HeartbeatRequest.SerializeToString,
            highbar_dot_coordinator__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/highbar.v1.HighBarCoordinator/PushState',
            highbar_dot_state__pb2.StateUpdate.SerializeToString,
            highbar_dot_coordinator__pb2.PushAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenCommandChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/highbar.v1.HighBarCoordinator/OpenCommandChannel',
            highbar_dot_coordinator__pb2.CommandChannelSubscribe.SerializeToString,
            highbar_dot_commands__pb2.CommandBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
