# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from highbar import callbacks_pb2 as highbar_dot_callbacks__pb2
from highbar import commands_pb2 as highbar_dot_commands__pb2
from highbar import service_pb2 as highbar_dot_service__pb2
from highbar import state_pb2 as highbar_dot_state__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in highbar/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HighBarProxyStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    The single service HighBarV3 exposes to clients. All RPCs share this
    surface so that observability counters and operational controls live
    on the same auth-and-transport plane as state and commands.

    Role model:
    - `Hello`, `StreamState`, `GetRuntimeCounters`: observer-legal
    (no token required for StreamState; see FR-013).
    - `SubmitCommands`, `InvokeCallback`, `Save`, `Load`: AI-role
    only; require the per-session token in metadata
    `x-highbar-ai-token` (FR-014).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/highbar.v1.HighBarProxy/Hello',
                request_serializer=highbar_dot_service__pb2.HelloRequest.SerializeToString,
                response_deserializer=highbar_dot_service__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/highbar.v1.HighBarProxy/StreamState',
                request_serializer=highbar_dot_service__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=highbar_dot_state__pb2.StateUpdate.FromString,
                _registered_method=True)
        self.SubmitCommands = channel.stream_unary(
                '/highbar.v1.HighBarProxy/SubmitCommands',
                request_serializer=highbar_dot_commands__pb2.CommandBatch.SerializeToString,
                response_deserializer=highbar_dot_service__pb2.CommandAck.FromString,
                _registered_method=True)
        self.InvokeCallback = channel.unary_unary(
                '/highbar.v1.HighBarProxy/InvokeCallback',
                request_serializer=highbar_dot_callbacks__pb2.CallbackRequest.SerializeToString,
                response_deserializer=highbar_dot_callbacks__pb2.CallbackResponse.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/highbar.v1.HighBarProxy/Save',
                request_serializer=highbar_dot_service__pb2.SaveRequest.SerializeToString,
                response_deserializer=highbar_dot_service__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.Load = channel.unary_unary(
                '/highbar.v1.HighBarProxy/Load',
                request_serializer=highbar_dot_service__pb2.LoadRequest.SerializeToString,
                response_deserializer=highbar_dot_service__pb2.LoadResponse.FromString,
                _registered_method=True)
        self.GetRuntimeCounters = channel.unary_unary(
                '/highbar.v1.HighBarProxy/GetRuntimeCounters',
                request_serializer=highbar_dot_service__pb2.CountersRequest.SerializeToString,
                response_deserializer=highbar_dot_service__pb2.CountersResponse.FromString,
                _registered_method=True)
        self.RequestSnapshot = channel.unary_unary(
                '/highbar.v1.HighBarProxy/RequestSnapshot',
                request_serializer=highbar_dot_service__pb2.RequestSnapshotRequest.SerializeToString,
                response_deserializer=highbar_dot_service__pb2.RequestSnapshotResponse.FromString,
                _registered_method=True)


class HighBarProxyServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    The single service HighBarV3 exposes to clients. All RPCs share this
    surface so that observability counters and operational controls live
    on the same auth-and-transport plane as state and commands.

    Role model:
    - `Hello`, `StreamState`, `GetRuntimeCounters`: observer-legal
    (no token required for StreamState; see FR-013).
    - `SubmitCommands`, `InvokeCallback`, `Save`, `Load`: AI-role
    only; require the per-session token in metadata
    `x-highbar-ai-token` (FR-014).
    """

    def Hello(self, request, context):
        """Version-handshake + session establishment. MUST be the first call
        on a new channel. Strict-equality schema-version check (FR-022a).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Server-streaming state feed. First message is a StateUpdate
        whose payload is a StateSnapshot; subsequent messages are
        StateDeltas or KeepAlives. Observers may call without a token;
        the AI role calls this alongside its command stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitCommands(self, request_iterator, context):
        """Client-streaming command submission. AI role only. Bounded queue
        — overflow returns RESOURCE_EXHAUSTED synchronously (FR-012a).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeCallback(self, request, context):
        """Unary synchronous engine-callback invocation. AI role only.
        Used by the plugin to forward engine callbacks (e.g., unit-def
        lookups) that the external AI needs to answer synchronously.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Unary synchronous save-game request. AI role only. Engine needs
        the response before it continues (architecture doc §Critical
        Pitfalls #6).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Unary synchronous load-game request. AI role only. Symmetric to
        Save.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeCounters(self, request, context):
        """Observability counters (FR-024, clarification Q1). Available to
        any authenticated client — same token as the AI role. Returns a
        coherent snapshot of RuntimeCounters; implementations take
        atomic reads, no global lock.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestSnapshot(self, request, context):
        """NEW (003-snapshot-arm-coverage).

        Request an out-of-cadence StateSnapshot. The plugin emits exactly
        one extra snapshot on the next engine frame following the RPC,
        regardless of how many concurrent callers made the request. The
        snapshot arrives on the caller's existing `StreamState`
        subscription — this RPC does not itself return snapshot data.

        AI role only (same token as SubmitCommands); observers use the
        periodic tick or their existing StreamState resume path.

        Use sparingly — the plugin guards against DoS via the
        1-per-frame coalescing described in FR-006.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HighBarProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=highbar_dot_service__pb2.HelloRequest.FromString,
                    response_serializer=highbar_dot_service__pb2.HelloResponse.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=highbar_dot_service__pb2.StreamStateRequest.FromString,
                    response_serializer=highbar_dot_state__pb2.StateUpdate.SerializeToString,
            ),
            'SubmitCommands': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitCommands,
                    request_deserializer=highbar_dot_commands__pb2.CommandBatch.FromString,
                    response_serializer=highbar_dot_service__pb2.CommandAck.SerializeToString,
            ),
            'InvokeCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeCallback,
                    request_deserializer=highbar_dot_callbacks__pb2.CallbackRequest.FromString,
                    response_serializer=highbar_dot_callbacks__pb2.CallbackResponse.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=highbar_dot_service__pb2.SaveRequest.FromString,
                    response_serializer=highbar_dot_service__pb2.SaveResponse.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=highbar_dot_service__pb2.LoadRequest.FromString,
                    response_serializer=highbar_dot_service__pb2.LoadResponse.SerializeToString,
            ),
            'GetRuntimeCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeCounters,
                    request_deserializer=highbar_dot_service__pb2.CountersRequest.FromString,
                    response_serializer=highbar_dot_service__pb2.CountersResponse.SerializeToString,
            ),
            'RequestSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestSnapshot,
                    request_deserializer=highbar_dot_service__pb2.RequestSnapshotRequest.FromString,
                    response_serializer=highbar_dot_service__pb2.RequestSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'highbar.v1.HighBarProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('highbar.v1.HighBarProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HighBarProxy(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    The single service HighBarV3 exposes to clients. All RPCs share this
    surface so that observability counters and operational controls live
    on the same auth-and-transport plane as state and commands.

    Role model:
    - `Hello`, `StreamState`, `GetRuntimeCounters`: observer-legal
    (no token required for StreamState; see FR-013).
    - `SubmitCommands`, `InvokeCallback`, `Save`, `Load`: AI-role
    only; require the per-session token in metadata
    `x-highbar-ai-token` (FR-014).
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarProxy/Hello',
            highbar_dot_service__pb2.HelloRequest.SerializeToString,
            highbar_dot_service__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/highbar.v1.HighBarProxy/StreamState',
            highbar_dot_service__pb2.StreamStateRequest.SerializeToString,
            highbar_dot_state__pb2.StateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitCommands(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/highbar.v1.HighBarProxy/SubmitCommands',
            highbar_dot_commands__pb2.CommandBatch.SerializeToString,
            highbar_dot_service__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarProxy/InvokeCallback',
            highbar_dot_callbacks__pb2.CallbackRequest.SerializeToString,
            highbar_dot_callbacks__pb2.CallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarProxy/Save',
            highbar_dot_service__pb2.SaveRequest.SerializeToString,
            highbar_dot_service__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarProxy/Load',
            highbar_dot_service__pb2.LoadRequest.SerializeToString,
            highbar_dot_service__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarProxy/GetRuntimeCounters',
            highbar_dot_service__pb2.CountersRequest.SerializeToString,
            highbar_dot_service__pb2.CountersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/highbar.v1.HighBarProxy/RequestSnapshot',
            highbar_dot_service__pb2.RequestSnapshotRequest.SerializeToString,
            highbar_dot_service__pb2.RequestSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
