// SPDX-License-Identifier: GPL-2.0-only
//
// HighBarV3 — compile-time schema version (T014, FR-022a).
//
// The plugin and every generated client stub compare this value with
// string equality on the Hello handshake. Mismatch → the server
// closes the session with FAILED_PRECONDITION before it becomes
// ACTIVE (data-model §9, contracts/README §Hello).
//
// Rules for bumping:
//   - Additive changes to proto files that DO NOT reorder oneof arms,
//     renumber fields, or change wire types: bump the PATCH component
//     (1.0.0 → 1.0.1).
//   - Additive changes that introduce new oneof arms, new messages,
//     or new RPCs: bump MINOR (1.0.0 → 1.1.0).
//   - Any breaking change (field removal, type change, renumbering):
//     requires a sibling `highbar.v2` package; do NOT edit this file.
//     See docs/architecture.md §Critical Pitfalls and
//     research.md §6 (strict-equality rationale).
//
// Every bump MUST be released as a matched trio: plugin + F# client +
// Python client. Strict-equality means any mismatch is a loud,
// fast-fail error instead of a silent runtime heisenbug.

#pragma once

namespace highbar::v1 {

inline constexpr const char* kSchemaVersion = "1.0.0";

}  // namespace highbar::v1
